# ------------------------------------------------------------------------------
# ⚠️ WARNING: DO NOT EDIT THIS FILE MANUALLY
# Generated by the gRPC Python protocol compiler plugin.
# ------------------------------------------------------------------------------
import grpc

from . import brain_service_pb2 as brain__service__pb2

class BrainOracleStub(object):
    """العميل (Client): يستخدمه من يريد إرسال طلب للعقل
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeContext = channel.unary_unary(
                '/alpha.brain.BrainOracle/AnalyzeContext',
                request_serializer=brain__service__pb2.ContextRequest.SerializeToString,
                response_deserializer=brain__service__pb2.ContextAnalysis.FromString,
                )
        self.PredictTrajectory = channel.unary_unary(
                '/alpha.brain.BrainOracle/PredictTrajectory',
                request_serializer=brain__service__pb2.PredictionRequest.SerializeToString,
                response_deserializer=brain__service__pb2.PredictionResponse.FromString,
                )
        self.ConsultStrategy = channel.unary_unary(
                '/alpha.brain.BrainOracle/ConsultStrategy',
                request_serializer=brain__service__pb2.TradeProposal.SerializeToString,
                response_deserializer=brain__service__pb2.StrategyVerdict.FromString,
                )


class BrainOracleServicer(object):
    """الخادم (Server): الفئة الأساسية التي يجب أن نكتب منطقنا بداخلها
    """

    def AnalyzeContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictTrajectory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainOracleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeContext': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeContext,
                    request_deserializer=brain__service__pb2.ContextRequest.FromString,
                    response_serializer=brain__service__pb2.ContextAnalysis.SerializeToString,
            ),
            'PredictTrajectory': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictTrajectory,
                    request_deserializer=brain__service__pb2.PredictionRequest.FromString,
                    response_serializer=brain__service__pb2.PredictionResponse.SerializeToString,
            ),
            'ConsultStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultStrategy,
                    request_deserializer=brain__service__pb2.TradeProposal.FromString,
                    response_serializer=brain__service__pb2.StrategyVerdict.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alpha.brain.BrainOracle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))